# application.yml
app:
  name: @project.name@
  environment: development
  description: ${app.name} ${app.version} est @project.description@
  version: @project.version@

# Logging properties
logging:
  level:
    root: INFO   # Root logger level
    org.springframework.web: ERROR
    com.popcodelab.mddapi: DEBUG
    org.hibernate: ERROR
  file:
    name: logs/${app.name}.log  # Log file name and location
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"  # Console log pattern
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"     # File log pattern

# Database properties
spring:
  datasource:
    url: jdbc:mysql://${APP_DB_HOST}:${APP_DB_PORT}/${APP_DB_NAME}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}


